config/routes.rb
Shopster::Application.routes.draw do
  get '/coupons/gdeslon/:id(.:format)', to: 'coupons#gdeslon_show', as: 'gdeslon_show'
  delete '/coupons/gdeslon/:id(.:format)', to: 'coupons#gdeslon_destroy', as: 'gdeslon_destroy'
  get '/coupons/8coupons/:id(.:format)', to: 'coupons#ninecoupons_show', as: 'ninecoupons_show'
  delete '/coupons/8coupons/:id(.:format)', to: 'coupons#ninecoupons_destroy', as: 'ninecoupons_destroy'
  get "coupons/"  =>   'coupons#index'

end

app/models/gdeslon/gdeslon_categories.rb
class GdeslonCategories < ActiveRecord::Base
  validates_uniqueness_of :id
end

app/models/gdeslon/gdeslon_coupon.rb
class GdeslonCoupon < ActiveRecord::Base
  has_one :gdeslon_merchant
  has_one :gdeslon_kind
  has_many :gdeslon_coupon_categories
  validates_uniqueness_of :coupon_id


end

app/models/gdeslon/gdeslon_coupon_categories.rb
class GdeslonCouponCategories < ActiveRecord::Base
  validates_uniqueness_of :id
end

app/models/gdeslon/gdeslon_kinds.rb
class GdeslonKinds < ActiveRecord::Base
  validates_uniqueness_of :id
end

app/models/gdeslon/gdeslon_merchant.rb
class GdeslonMerchant < ActiveRecord::Base
  has_many :gdeslon_coupons
  has_many :gdeslon_categories
  validates_uniqueness_of :id
end

app/models/nine_coupon_coupon.rb
class NineCouponCoupon < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController

  def index
   @coupons = GdeslonCoupon.all
   @coupons = GdeslonCoupon.page(params[:page]) if params[:db] === 'gdeslon'
   @coupons = NineCouponCoupon.page(params[:page]) if params[:db] === '8coupons'
  end

  def gdeslon_show
    render_404 unless @coupon = GdeslonCoupon.find_by_id(params[:id])
  end

  def gdeslon_destroy
    @coupon = GdeslonCoupon.find_by_id(params[:id])
    @coupon.destroy
  end

  def ninecoupons_show
     render_404 unless @coupon = NineCouponCoupon.find_by_id(params[:id])
  end

  def ninecoupons_destroy
    @coupon = NineCouponCoupon.find_by_id(params[:id])
    @coupon.destroy
  end
  private

  def render_404
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/coupons_helper.rb
module CouponsHelper

  def get_kind(s)
    kind = GdeslonKinds.find_by_id(s)
    kind.name
  end

  def get_merchant(s)
    merchant = GdeslonMerchant.find_by_id(s)
    merchant.name if merchant
  end


end

app/views/coupons/_gdeslon_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= label_tag t('gdeslon.label_name')
      %th= label_tag t('gdeslon.label_kind')
      %th= label_tag t('gdeslon.label_url')
      %th= label_tag t('gdeslon.label_date_start')
      %th= label_tag t('gdeslon.label_date_end')
      %th
  %tbody
    - for coupon in @coupons do
      %tr{:class => "gdeslon.#{coupon.id}"}
        %td= link_to coupon.name, gdeslon_show_path(coupon)
        %td= get_kind(coupon.gdeslon_kind_id)
        %td= link_to t('gdeslon.label_url_click'), coupon.url.to_s
        %td= coupon.date_start
        %td= coupon.date_end
        %td
          .delete_action
            %span.glyphicon.glyphicon-trash

= paginate @coupons

app/views/coupons/_ninecoupons_table.html.haml
%table.table.table-hover
  %thead
    %tr
      %th= label_tag t('8coupons.label_name')
      %th= label_tag t('8coupons.label_address')
      %th= label_tag t('8coupons.label_url')
      %th= label_tag t('8coupons.label_date_start')
      %th= label_tag t('8coupons.label_date_end')
      %th
  %tbody
    - for coupon in @coupons do
      %tr{:class => "8coupons.#{coupon.id}"}
        %td= link_to coupon.name, ninecoupons_show_path(coupon)
        %td= coupon.city + ", " + coupon.address
        %td= link_to t('8coupons.label_url_click'), coupon.url.to_s
        %td= coupon.date_start
        %td= coupon.date_end
        %td
          .delete_action
            %span.glyphicon.glyphicon-trash

= paginate @coupons

app/views/coupons/_no_select.html.haml
.jumbotron
  %h1
    = t("label_hello")
  %p
    = t("label_jumbotron")
  %p
    = t("label_thanks")

app/views/coupons/gdeslon_destroy.html.haml
:javascript
  window.location.href="/coupons?db=gdeslon"

app/views/coupons/gdeslon_show.html.haml
.page-header
  %h1=t('label_coupon')
%p
  %ul.nav.nav-tabs
    %li.active
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === 'gdeslon'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === '8coupons'
    %li
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === '8coupons'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === 'gdeslon'


%div
  %fieldset
    %p
      %label
        = t('gdeslon.label_name')
        \:
        = @coupon.name
    %p
      %label
        = t('gdeslon.label_description')
        \:
        = @coupon.description
    %p
      %label
        = t('gdeslon.label_kind')
        \:
        =get_kind(@coupon.gdeslon_kind_id) if @coupon.gdeslon_kind_id
    %p
      %label
        = t('gdeslon.merchant')
        \:
        = get_merchant(@coupon.gdeslon_merchant_id) if @coupon.gdeslon_merchant_id
    %p
      %label
        = t('gdeslon.label_url')
        \:
        = link_to t('gdeslon.label_url_click'), @coupon.url
    %p
      %label
        = t('gdeslon.label_date_start')
        \:
        = @coupon.date_start
    %p
      %label
        = t('gdeslon.label_date_end')
        \:
        = @coupon.date_end
    %p
      %label
        = t('gdeslon.label_code')
        \:
        = @coupon.code
    %p
      =button_to t('label_destroy'), {:controller => "coupons", :action => "gdeslon_destroy"}, :method => "delete" , :class => "btn btn-danger", form: { :from_show => 1 }

app/views/coupons/index.html.haml
.page-header
  %h1=t('label_coupon_plural')
%p
  %ul.nav.nav-tabs
    %li.active
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === 'gdeslon'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === '8coupons'
    %li
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === '8coupons'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === 'gdeslon'

  =render :partial => 'coupons/no_select' unless params[:db]
  =render :partial => 'coupons/gdeslon_table', :locals => { :coupons => @coupons } if params[:db] === 'gdeslon'
  =render :partial => 'coupons/ninecoupons_table', :locals => { :coupons => @coupons } if params[:db] === '8coupons'

app/views/coupons/ninecoupons_destroy.html.haml
:javascript
  window.location.href="/coupons?db=8coupons"

app/views/coupons/ninecoupons_show.html.haml
.page-header
  %h1=t('label_coupon')
%p
  %ul.nav.nav-tabs
    %li.active
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === 'gdeslon'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === '8coupons'
    %li
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} unless params[:db]
      = link_to t("gdeslon.label"), {:controller => 'coupons', :action => 'index', :db => 'gdeslon'} if params[:db] === '8coupons'
      = link_to t("8coupons.label"), {:controller => 'coupons', :action => 'index', :db => '8coupons'} if params[:db] === 'gdeslon'

.row
  .col-md-6
    %div
      %fieldset
        %p
          %label
            = t('8coupons.label_name')
            \:
            = @coupon.name
        %p
          %label
            = t('8coupons.label_description')
            \:
            = @coupon.description
        %p
          %label
            = t('8coupons.label_address')
            \:
            =@coupon.city + ", " + @coupon.address
        %p
          %label
            = t('8coupons.store_id')
            \:
            = @coupon.store_id
        %p
          %label
            = t('8coupons.label_url')
            \:
            = link_to t('8coupons.label_url_click'), @coupon.url
        %p
          %label
            = t('8coupons.label_date_start')
            \:
            = @coupon.date_start
        %p
          %label
            = t('8coupons.label_date_end')
            \:
            = @coupon.date_end
        %p
          =button_to t('label_destroy'), {:controller => "coupons", :action => "ninecoupons_destroy"}, :method => "delete" , :class => "btn btn-danger", data: { :from_show => 1 }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopster</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">

    <div class="span10">
      <%= yield %>
    </div>

</div>

<div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"></div>
  <div class="col-md-1"><address>
    <strong>Alexander Gornov</strong><br>
    <a href="mailto:zmokizmoghi@gmail.com">zmokizmoghi@gmail.com</a>
  </address></div>
  <div class="col-md-1"></div>
</body>
</html>